name: 'Terraform AWS CloudFront'
description: 'Configure CloudFront using Terraform'

inputs:
  project-name:
    description: 'The project name used for naming resources and tags'
    required: true

  root-domain:
    description: 'The main domain for the application (e.g., "example.com")'
    required: true

  terraform-dir:
    description: 'Directory where the Terraform code is located'
    required: true

  aws-region:
    description: 'AWS region for deployment'
    required: false
    default: 'us-east-1'

  subdomain:
    description: 'Subdomain (e.g., app or www)'
    required: false
    default: 'app'

  environment:
    description: 'Deployment environment (e.g., dev, prod, staging)'
    required: false
    default: 'dev'

  origin-domain-name:
    description: 'Origin domain name (typically S3 static site bucket domain)'
    required: true

  logging-bucket-domain-name:
    description: 'Logging bucket domain name for CloudFront logs'
    required: true

  cloudfront-distribution-name:
    description: 'Custom CloudFront distribution name'
    required: false
    default: 'null'

  ssl-minimum-protocol-version:
    description: 'The minimum TLS version CloudFront accepts'
    required: false
    default: 'TLSv1.2_2021'

  tags:
    description: 'Extra tags for resources (JSON string)'
    required: false
    default: '{}'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Terraform Init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan \
          -var="project_name=${{ inputs.project-name }}" \
          -var="root_domain=${{ inputs.root-domain }}" \
          -var="subdomain=${{ inputs.subdomain }}" \
          -var="aws_region=${{ inputs.aws-region }}" \
          -var="environment=${{ inputs.environment }}" \
          -var="origin_domain_name=${{ inputs.origin-domain-name }}" \
          -var="logging_bucket_domain_name=${{ inputs.logging-bucket-domain-name }}" \
          -var="cloudfront_distribution_name=${{ inputs.cloudfront-distribution-name }}" \
          -var="ssl_minimum_protocol_version=${{ inputs.ssl-minimum-protocol-version }}" \
          -var='tags=${{ inputs.tags }}' \
          -out=tfplan
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}

    - name: Terraform Apply with Retry
      id: apply
      continue-on-error: true
      run: |
        for attempt in {1..5}; do
          if terraform apply -auto-approve tfplan; then
            echo "Terraform apply succeeded on attempt $attempt"
            echo "apply_success=true" >> $GITHUB_ENV
            break
          else
            echo "Attempt $attempt failed. Retrying in 120 seconds..."
            sleep 120
            if [ $attempt -eq 5 ]; then
              echo "Terraform apply failed after 5 attempts"
              echo "apply_success=false" >> $GITHUB_ENV
              exit 1
            fi
          fi
        done
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}

    - name: Terraform Destroy on Failure
      if: env.apply_success == 'false'
      run: |
        echo "Cleaning up resources with terraform destroy..."
        terraform destroy -auto-approve \
          -var="project_name=${{ inputs.project-name }}" \
          -var="root_domain=${{ inputs.root-domain }}" \
          -var="subdomain=${{ inputs.subdomain }}" \
          -var="aws_region=${{ inputs.aws-region }}" \
          -var="environment=${{ inputs.environment }}" \
          -var="origin_domain_name=${{ inputs.origin-domain-name }}" \
          -var="logging_bucket_domain_name=${{ inputs.logging-bucket-domain-name }}" \
          -var="cloudfront_distribution_name=${{ inputs.cloudfront-distribution-name }}" \
          -var="ssl_minimum_protocol_version=${{ inputs.ssl-minimum-protocol-version }}" \
          -var='tags=${{ inputs.tags }}'
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}

    - name: Get Terraform Outputs
      if: env.apply_success == 'true'
      id: outputs
      run: |
        echo "s3_bucket_name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
        echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}
